### ISSUE TITLE
problem in seq2seq

### ISSUE THREAD

**Issue by lisanka93** [adeshpande3/Facebook-Messenger-Bot#1]
def idsToSentence(ids, wList):

    print "ids", type(ids)
    EOStokenIndex = wList.index('<EOS>')
    padTokenIndex = wList.index('<pad>')
    print "indexes", EOStokenIndex, padTokenIndex
    myStr = ""
    listOfResponses=[]

    for num in ids:

        if (num[0] == EOStokenIndex or num[0] == padTokenIndex):

            myStr = ""
        else:
            myStr = myStr + wList[num[0]] + " "

    if myStr:
        listOfResponses.append(myStr)
    listOfResponses = [i for i in listOfResponses if i]
    print "listof restp", listOfResponses[:10]
    return listOfResponses

i never seem to get to the "else" in the loop - the num is alwas <pad> and i therefore create no responses - how is that possible?

**Comment by adeshpande3** [comment]
This is normal behavior for the chatbot at the beginning of training. Like I mentioned in my [blog post](https://adeshpande3.github.io/adeshpande3.github.io/How-I-Used-Deep-Learning-to-Train-a-Chatbot-to-Talk-Like-Me), the chatbot will only output padding and EOS tokens for the first couple hundred/thousand iterations since those are the most frequently seen in the dataset. As the seq2seq model trains for longer, then you'll start to see outputs that are a bit more varied, and that's when num[0] will be something other than pad/EOS and it'll go into the else portion of the loop. 

So, just train for a bit longer, and see if you still see this behavior. Let me know if you're still coming across issues.
