### ISSUE TITLE
How To Know If The Model Is Trained?

### ISSUE THREAD

**Issue by Sunehildeep** [adeshpande3/Facebook-Messenger-Bot#31]
How to know if the model is fully trained? I'm at around 200k iteration, but how would I know its trained?
And I've one more question, does the model learns/improves itself as we keep chatting with it?

**Comment by Sunehildeep** [comment]
Okay, thanks for the info.

**Comment by Sunehildeep** [comment]
I've one more question, should I delete all other checkpoints when I've to deploy it and only keep the latest one? And also, I saved the training and restored it now, so does that mean that the checkpoint numbers will differ? Or they will continue from where I left them. For example if I stopped training at 60k iterations and the checkpoint was named as 60000 so if I restore my training, will it create checkpoints from 10000 or from 70000.

One more thing I'd like to know is how do I modify the bot to improve its responses as we keep chatting with it? Like if it gives wrong responses, then if we keep chatting with it, it keeps learning how I speak? Because I've seen this feature in nearly every chatbot. I only liked your chatbot and I'm a noob in tensorflow, so sorry for the "too" many questions I've been asking. I'd just like to get this information which is confusing me.

**Comment by adeshpande3** [comment]
1) You won't have to delete the other checkpoints because it looks like from Tensorflow's [documentation](https://www.tensorflow.org/api_docs/python/tf/train/latest_checkpoint) it will always take the latest checkpoint. And yes, the checkpoint numbers will differ because the variable i for the number of iterations will restart at 0. It'll create checkpoints from 10000 instead of 70000 I believe (although best way to check is just to try it out). 

2) I'm not aware of any bots that have that behaviour. It doesn't really seem possible to me because you would need a way to tell the network that the response was incorrect and you would need to be able to show the network what the expected output was. Maybe you can link to the other chatbots that have that behavior and I can try to see what they are doing. 

3) I'm not really aware of any slowdown that could occur but maybe you should try decreasing the size of the network and then seeing if the problem is still there.

**Comment by Sunehildeep** [comment]
I'm not able to find the chatbot I saw, but the example in there was like this.
User: Hi
Bot: aaa

(After chatting for a few minutes)
User: hey
Bot: hello


I believe it gets the response and trains the bot with 1 iteration (which basically means the training code for one time) with respect to that response while chatting.

**Comment by Sunehildeep** [comment]
You are right, but I've one more issue, I've trained for like 300k iterations but still I get invalid responses and random outputs. Everytime it replies same reply to a specific word and that reply is also invalid.
For example:
User: Ok
Bot: I mean

User: Hi
Bot: And emailed it

**Comment by adeshpande3** [comment]
See https://github.com/adeshpande3/Facebook-Messenger-Bot/issues/30

**Comment by Sunehildeep** [comment]
"By decreasing the complexity of the network, I mean decreasing the number of LSTM units or the number of LSTM layers"
I did tried that, but the thing is when I decrease LSTM units I get tensorflow error of shape not matching. of lhs and rhs

**Comment by Sunehildeep** [comment]
So if I want to change the lstm unit for training, I need to start everything from beginning? Like I'm on 500k iterations now and the bot just responds with 3 messages to every sentence

**Comment by adeshpande3** [comment]
Yeah you need to restart the training. 

As a side note, I should make it clear that the network I've created is just a basic one and likely isn't enough to achieve good performance. If you want an extremely realistic chatbot, you'll need to take a look at some research papers to see their implementations. I referenced some at the end of [this post](https://adeshpande3.github.io/adeshpande3.github.io/How-I-Used-Deep-Learning-to-Train-a-Chatbot-to-Talk-Like-Me) and I recommend you take a look at the Ways to Improve section.

**Comment by Sunehildeep** [comment]
Thanks, I'll look into them and If I'm able to improve this chatbot, I will contribute.

I'm closing the issue now as my problems are solved.
