### ISSUE TITLE
"Update" model by expanding training set?

### ISSUE THREAD

**Issue by VCDragoon** [adeshpande3/Facebook-Messenger-Bot#46]
I successfully got a little chatbot up and running using my FB data -- training it took ~ 8 hours (~150,000 records) or so but it's not too bad.  It gives a good base.

I'm wondering how I can improve on the results over time.  The most obvious way to me is to extract more data from other sources and "update" the model by continuing training on more data.  Is there a way to do this without having to retrain from scratch?

When I remove the comment that lets you load in a saved model (I think it's line 202?) and run seq2seq, the initial outputs look like they are training from scratch again - I get [] outputs for the first several thousand runs, and then outputs that look primitive...

Alternatively, is there any possibility of using the trained model in a reinforcement learning process to help it perform better over time?  I'm happy to do the research and work on this if you can point me in the right direction!

(Thanks for the great tutorial by the way!!!)

**Comment by adeshpande3** [comment]
Hmm, it's been a while since I've worked with this code but I believe in addition to removing the comment on [this line](https://github.com/adeshpande3/Facebook-Messenger-Bot/blob/master/Seq2Seq.py#L201), you also need to comment the next line out because running that will re-initialize all the weights to random values. Not completely sure if I'm remembering correctly but you can try that to fix that saved model issue. 

In terms of other approaches like using RL, I'm not completely familiar with the state of the art currently, but at the end of my [blog post](https://adeshpande3.github.io/adeshpande3.github.io/How-I-Used-Deep-Learning-to-Train-a-Chatbot-to-Talk-Like-Me), I referenced some relevant papers that could point you in a better direction. 

This [repo](https://github.com/yaserkl/RLSeq2Seq) and the associated paper seems like it could be something to look into.

**Comment by VCDragoon** [comment]
Wow thanks for the quick response!  I'll poke around and let you know how it goes :)

**Comment by VCDragoon** [comment]
I spent way too long trying to figure this out, but you were exactly right - commenting out the following line put me right back with the same model.

Thank you!!

**Comment by adeshpande3** [comment]
Awesome, sorry you had to go through that trouble. I definitely should've made it more clear, I updated the comments accordingly. And yeah, if you find anything interesting, be sure to post on this issue. Would be helpful for anyone looking to improve on this project and get better results :)
