### ISSUE TITLE
Discord Data Parse Error #2

### ISSUE THREAD

**Issue by Solixity** [adeshpande3/Facebook-Messenger-Bot#64]
*Extension of Issue #63*

I'm currently going through what #63 was going through, the directory length is always 0. 
![image](https://user-images.githubusercontent.com/55036292/108796973-06684280-7558-11eb-8ff8-4f1140253e54.png)

When I attempt to test a small cut out of my Discord Message data (as you can see [here](https://regex101.com/r/UJFIjf/1), that was originally made from [this](https://regex101.com/r/G3N2Ep/1)), it continues to return no matches at all. I have not modified any part of the script *or* the exported data, what's going on and how can I manage to fix it?

**Comment by ThatLonelyMozza** [comment]
I'd like to add on that if I need to show exported data, I will, but the other person in the data will be anonymous due to their preference.

**Comment by TotallyNotChase** [comment]
Interesting, Your format seems to have 3 newline as separators between messages instead of 2. I try to refrain from greedy matching newlines but if there's inconsistency in the number of newlines in formats - that should be the only solution.

Also, note that in the regex link you posted - you're missing the `#` in your name. This won't fix the problem at hand. But if you also go ahead and cut down the 3 newlines down to 2, [you'll see them match](https://regex101.com/r/ekQBzV/2).

Here's also the [matches from the other perspective](https://regex101.com/r/TtBISP/1)

Could you confirm that the separators for each message in your exported format is indeed 3 newlines? If this is the case. I'll just switch the newline matchers to greedy and roll out a fix.

Note that this is in no way related to #63 as the format provided there matches successfully in the regex tester.

**Comment by ThatLonelyMozza** [comment]
> Note that this is in no way related to #63 as the format provided there matches successfully in the regex tester.

My fault, I thought that it was related due to how it was dealing with the same data and how the regex wasn't able to parse data. I'll go ahead and double check if there's 3 newlines instead of 2. I haven't modified the data as said (other than anonymizing the other person in this case) so there _may_ be 3 newlines. Thanks for the help so far though.

**Comment by Solixity** [comment]
Closed it due to it being a stale issue.
